// <auto-generated />
using APICrudServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPICrud.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20231226040119_Mobile")]
    partial class Mobile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APICrudServer.Data.Mobile", b =>
                {
                    b.Property<int>("Mobile_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MobilePrice")
                        .HasColumnType("int");

                    b.Property<string>("Mobile_Brand_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile_Model_Name")
                        .HasColumnType("longtext");

                    b.HasKey("Mobile_Id");

                    b.ToTable("Mobiles");
                });
#pragma warning restore 612, 618
        }
    }
}
